### ISSUE TITLE
As a designer, I want to design character behaviour

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#49]
Consider the kinds of behaviour the enemies could have. For example, the red enemy is tall, so it might be that the main character cannot avoid this enemy without a powerup

Estimated: 1h

**Comment by benattebery** [comment]
Ideas for the behaviors:
Froger:
As he flips over and can walk on his hands we should make it to where to character can only jump over him while he is bent over while he is transitioning from hands to feet and vice versa. He could be mixed into any of the levels as he does not require a power up to defeat. Otherwise we could make him jump and while he jumps is when he flips from hands to feet and vise versa during his jump is when the character can run underneath him to pass him. He is slow to turn and chase, but a quick jumper so the player will have to use a timing twitch mechanic.
Red Enemy:
He is tall and somewhat slow but we could design him to travel in relative groups and little packs. For example there could be 3 in a row, evenly spaced, and the character has to perfectly time each double jump to get over them. Making timing crucial, with a little bit of repetition. This sort of enemy might not chase, but rather patrol, so that the pattern is not lost as the character tries to jump between each enemy. If we make them follow the character when in a tight formation like that the character may become overwhelmed and might not be able to jumpe over the 3rd one for example. But this could be tested and tried to find the best behavior.
Scorpion:
Scorpion is super fast and requires the speed metabolizer power up. They will chase the character vigorously and can turn very quickly relative to the other enemies. The character can jump over it. The player must utilize quick reactions as this enemy will come at the character very quickly and if the player does not "have his head on a swivel" they will lose. These enemies could be lethal to each other, so when they charge at the character from opposite sides the player can utilize this by jumping at the right moment and they hit each other defeating the themselves.
Snek:
This enemy can have a plethora of behaviors. I feel that a swarm of these could be interesting so the character has to stay high and out of the way from this enemy. It could even have an aura so you have to keep distance and if the character cant stay at the specified distance then they will perish. We could have it slither up walls to chase the character.
