### ISSUE TITLE
As a game designer, i want to playtest our game

### ISSUE THREAD

**Issue by GPJFlorge** [UoSGamesGroups/first-semester-group-1#57]
Get people to play our game, at least one person outside of our demographic. Try to get at least 2 people to play it

**Comment by benattebery** [comment]
I play tested the game and found a few bugs and ill list them below if any of these things are working as intended please ignore.
The game runs smoothly other than the fact that you can basically scale walls and it means you can get to areas you shouldn't and fall into the infinite abyss without dying.
The double jump feature doesn't reset after the 2nd jump so essentially the character can basically hover any perceived threat. essentially removing said threat and therefore making the challenge relatively non existent.
Right after the first enemy we go straight through to the next level inexplicably. Is this just for the demo?
I feel that we are slightly too zoomed in while playing and could have the field of vision a bit bigger. 
We are missing a few art assets like the spaceship. 
There was no way of stopping the demo (that I could tell anyway) so no menu implemented.

Otherwise this was cool and I could really see the potential and think it will be fun. 
Great work Gents!
